margin = 180
always_for_in = true
for_in_replacement = "in"
annotate_untyped_fields_with_any = false
whitespace_in_kwargs = false
always_use_return = true
format_docstrings = true
remove_extra_newlines = false
trailing_comma = false
join_lines_based_on_source = true
separate_kwargs_with_semicolon = true
whitespace_ops_in_indices = false