# Autogenerated using ProtoBuf.jl v1.3.0
# original file: zmq_messages.proto (proto3 syntax)

module zmq_messages_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export DataForFUSE, DataFromFUSE, FUSERequest, Ack


struct DataForFUSE
    sim_time::Float64
    done::Bool
    Ip_latest::Float64
    Ip_avg::Float64
    Bt::Float64
    pr15v::Float64
    I_coil::Vector{Float64}
    psizr::Vector{Float64}
    r_grid::Vector{Float64}
    z_grid::Vector{Float64}
    pinj_per_beam::Vector{Float64}
    nbi_acc_voltage::Vector{Float64}
    gas_cal::Vector{Float64}
end
PB.default_values(::Type{DataForFUSE}) = (;sim_time = zero(Float64), done = false, Ip_latest = zero(Float64), Ip_avg = zero(Float64), Bt = zero(Float64), pr15v = zero(Float64), I_coil = Vector{Float64}(), psizr = Vector{Float64}(), r_grid = Vector{Float64}(), z_grid = Vector{Float64}(), pinj_per_beam = Vector{Float64}(), nbi_acc_voltage = Vector{Float64}(), gas_cal = Vector{Float64}())
PB.field_numbers(::Type{DataForFUSE}) = (;sim_time = 1, done = 2, Ip_latest = 3, Ip_avg = 4, Bt = 5, pr15v = 6, I_coil = 7, psizr = 8, r_grid = 9, z_grid = 10, pinj_per_beam = 11, nbi_acc_voltage = 12, gas_cal = 13)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DataForFUSE}, _endpos::Int=0, _group::Bool=false)
    sim_time = zero(Float64)
    done = false
    Ip_latest = zero(Float64)
    Ip_avg = zero(Float64)
    Bt = zero(Float64)
    pr15v = zero(Float64)
    I_coil = PB.BufferedVector{Float64}()
    psizr = PB.BufferedVector{Float64}()
    r_grid = PB.BufferedVector{Float64}()
    z_grid = PB.BufferedVector{Float64}()
    pinj_per_beam = PB.BufferedVector{Float64}()
    nbi_acc_voltage = PB.BufferedVector{Float64}()
    gas_cal = PB.BufferedVector{Float64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            sim_time = PB.decode(d, Float64)
        elseif field_number == 2
            done = PB.decode(d, Bool)
        elseif field_number == 3
            Ip_latest = PB.decode(d, Float64)
        elseif field_number == 4
            Ip_avg = PB.decode(d, Float64)
        elseif field_number == 5
            Bt = PB.decode(d, Float64)
        elseif field_number == 6
            pr15v = PB.decode(d, Float64)
        elseif field_number == 7
            PB.decode!(d, wire_type, I_coil)
        elseif field_number == 8
            PB.decode!(d, wire_type, psizr)
        elseif field_number == 9
            PB.decode!(d, wire_type, r_grid)
        elseif field_number == 10
            PB.decode!(d, wire_type, z_grid)
        elseif field_number == 11
            PB.decode!(d, wire_type, pinj_per_beam)
        elseif field_number == 12
            PB.decode!(d, wire_type, nbi_acc_voltage)
        elseif field_number == 13
            PB.decode!(d, wire_type, gas_cal)
        else
            Base.skip(d, wire_type)
        end
    end
    return DataForFUSE(sim_time, done, Ip_latest, Ip_avg, Bt, pr15v, I_coil[], psizr[], r_grid[], z_grid[], pinj_per_beam[], nbi_acc_voltage[], gas_cal[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DataForFUSE)
    initpos = position(e.io)
    x.sim_time !== zero(Float64) && PB.encode(e, 1, x.sim_time)
    x.done != false && PB.encode(e, 2, x.done)
    x.Ip_latest !== zero(Float64) && PB.encode(e, 3, x.Ip_latest)
    x.Ip_avg !== zero(Float64) && PB.encode(e, 4, x.Ip_avg)
    x.Bt !== zero(Float64) && PB.encode(e, 5, x.Bt)
    x.pr15v !== zero(Float64) && PB.encode(e, 6, x.pr15v)
    !isempty(x.I_coil) && PB.encode(e, 7, x.I_coil)
    !isempty(x.psizr) && PB.encode(e, 8, x.psizr)
    !isempty(x.r_grid) && PB.encode(e, 9, x.r_grid)
    !isempty(x.z_grid) && PB.encode(e, 10, x.z_grid)
    !isempty(x.pinj_per_beam) && PB.encode(e, 11, x.pinj_per_beam)
    !isempty(x.nbi_acc_voltage) && PB.encode(e, 12, x.nbi_acc_voltage)
    !isempty(x.gas_cal) && PB.encode(e, 13, x.gas_cal)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DataForFUSE)
    encoded_size = 0
    x.sim_time !== zero(Float64) && (encoded_size += PB._encoded_size(x.sim_time, 1))
    x.done != false && (encoded_size += PB._encoded_size(x.done, 2))
    x.Ip_latest !== zero(Float64) && (encoded_size += PB._encoded_size(x.Ip_latest, 3))
    x.Ip_avg !== zero(Float64) && (encoded_size += PB._encoded_size(x.Ip_avg, 4))
    x.Bt !== zero(Float64) && (encoded_size += PB._encoded_size(x.Bt, 5))
    x.pr15v !== zero(Float64) && (encoded_size += PB._encoded_size(x.pr15v, 6))
    !isempty(x.I_coil) && (encoded_size += PB._encoded_size(x.I_coil, 7))
    !isempty(x.psizr) && (encoded_size += PB._encoded_size(x.psizr, 8))
    !isempty(x.r_grid) && (encoded_size += PB._encoded_size(x.r_grid, 9))
    !isempty(x.z_grid) && (encoded_size += PB._encoded_size(x.z_grid, 10))
    !isempty(x.pinj_per_beam) && (encoded_size += PB._encoded_size(x.pinj_per_beam, 11))
    !isempty(x.nbi_acc_voltage) && (encoded_size += PB._encoded_size(x.nbi_acc_voltage, 12))
    !isempty(x.gas_cal) && (encoded_size += PB._encoded_size(x.gas_cal, 13))
    return encoded_size
end

struct DataFromFUSE
    sim_time::Float64
    valid::Bool
    betap::Float64
    betap_dot::Float64
    li::Float64
    li_dot::Float64
    p_res::Float64
    dens_co2_sig::Vector{Float64}
end
PB.default_values(::Type{DataFromFUSE}) = (;sim_time = zero(Float64), valid = false, betap = zero(Float64), betap_dot = zero(Float64), li = zero(Float64), li_dot = zero(Float64), p_res = zero(Float64), dens_co2_sig = Vector{Float64}())
PB.field_numbers(::Type{DataFromFUSE}) = (;sim_time = 1, valid = 2, betap = 3, betap_dot = 4, li = 5, li_dot = 6, p_res = 7, dens_co2_sig = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DataFromFUSE}, _endpos::Int=0, _group::Bool=false)
    sim_time = zero(Float64)
    valid = false
    betap = zero(Float64)
    betap_dot = zero(Float64)
    li = zero(Float64)
    li_dot = zero(Float64)
    p_res = zero(Float64)
    dens_co2_sig = PB.BufferedVector{Float64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            sim_time = PB.decode(d, Float64)
        elseif field_number == 2
            valid = PB.decode(d, Bool)
        elseif field_number == 3
            betap = PB.decode(d, Float64)
        elseif field_number == 4
            betap_dot = PB.decode(d, Float64)
        elseif field_number == 5
            li = PB.decode(d, Float64)
        elseif field_number == 6
            li_dot = PB.decode(d, Float64)
        elseif field_number == 7
            p_res = PB.decode(d, Float64)
        elseif field_number == 8
            PB.decode!(d, wire_type, dens_co2_sig)
        else
            Base.skip(d, wire_type)
        end
    end
    return DataFromFUSE(sim_time, valid, betap, betap_dot, li, li_dot, p_res, dens_co2_sig[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DataFromFUSE)
    initpos = position(e.io)
    x.sim_time !== zero(Float64) && PB.encode(e, 1, x.sim_time)
    x.valid != false && PB.encode(e, 2, x.valid)
    x.betap !== zero(Float64) && PB.encode(e, 3, x.betap)
    x.betap_dot !== zero(Float64) && PB.encode(e, 4, x.betap_dot)
    x.li !== zero(Float64) && PB.encode(e, 5, x.li)
    x.li_dot !== zero(Float64) && PB.encode(e, 6, x.li_dot)
    x.p_res !== zero(Float64) && PB.encode(e, 7, x.p_res)
    !isempty(x.dens_co2_sig) && PB.encode(e, 8, x.dens_co2_sig)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DataFromFUSE)
    encoded_size = 0
    x.sim_time !== zero(Float64) && (encoded_size += PB._encoded_size(x.sim_time, 1))
    x.valid != false && (encoded_size += PB._encoded_size(x.valid, 2))
    x.betap !== zero(Float64) && (encoded_size += PB._encoded_size(x.betap, 3))
    x.betap_dot !== zero(Float64) && (encoded_size += PB._encoded_size(x.betap_dot, 4))
    x.li !== zero(Float64) && (encoded_size += PB._encoded_size(x.li, 5))
    x.li_dot !== zero(Float64) && (encoded_size += PB._encoded_size(x.li_dot, 6))
    x.p_res !== zero(Float64) && (encoded_size += PB._encoded_size(x.p_res, 7))
    !isempty(x.dens_co2_sig) && (encoded_size += PB._encoded_size(x.dens_co2_sig, 8))
    return encoded_size
end

struct FUSERequest
    status::String
    time::Float64
end
PB.default_values(::Type{FUSERequest}) = (;status = "", time = zero(Float64))
PB.field_numbers(::Type{FUSERequest}) = (;status = 1, time = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FUSERequest}, _endpos::Int=0, _group::Bool=false)
    status = ""
    time = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            status = PB.decode(d, String)
        elseif field_number == 2
            time = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return FUSERequest(status, time)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FUSERequest)
    initpos = position(e.io)
    !isempty(x.status) && PB.encode(e, 1, x.status)
    x.time !== zero(Float64) && PB.encode(e, 2, x.time)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FUSERequest)
    encoded_size = 0
    !isempty(x.status) && (encoded_size += PB._encoded_size(x.status, 1))
    x.time !== zero(Float64) && (encoded_size += PB._encoded_size(x.time, 2))
    return encoded_size
end

struct Ack
    status::String
    ok::Bool
    error::String
end
PB.default_values(::Type{Ack}) = (;status = "", ok = false, error = "")
PB.field_numbers(::Type{Ack}) = (;status = 1, ok = 2, error = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Ack}, _endpos::Int=0, _group::Bool=false)
    status = ""
    ok = false
    error = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            status = PB.decode(d, String)
        elseif field_number == 2
            ok = PB.decode(d, Bool)
        elseif field_number == 3
            error = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Ack(status, ok, error)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Ack)
    initpos = position(e.io)
    !isempty(x.status) && PB.encode(e, 1, x.status)
    x.ok != false && PB.encode(e, 2, x.ok)
    !isempty(x.error) && PB.encode(e, 3, x.error)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Ack)
    encoded_size = 0
    !isempty(x.status) && (encoded_size += PB._encoded_size(x.status, 1))
    x.ok != false && (encoded_size += PB._encoded_size(x.ok, 2))
    !isempty(x.error) && (encoded_size += PB._encoded_size(x.error, 3))
    return encoded_size
end
end # module
