FROM julia:latest
RUN apt-get -y update
RUN apt-get -y install git make
RUN apt-get autoclean

WORKDIR /root/.ssh
WORKDIR /root
COPY ./.sshFUSE/id_rsa .ssh/
COPY ./.sshFUSE/id_rsa.pub .ssh/
RUN echo '|1|GoanPSKwI62zZiz0fM7Ra1/bMnY=|RfL5HqeRizo17UPHv5heN3WSov0= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> .ssh/known_hosts
RUN echo '|1|vWHRPCMPcD+5qXk4DMgQaiEtdIw=|vIhA31/oZhH6DoxrtYTHwRs+hK0= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' >> .ssh/known_hosts
RUN echo '|1|3Ew2LGmHq9SoOt9RIi/aBQxOr98=|W0mClO1lwdZSw9hjg4ghlaqOVMw= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=' >> .ssh/known_hosts

WORKDIR /root/.julia/dev
RUN git config --global pull.rebase false
RUN git clone git@github.com:ProjectTorreyPines/FUSE.jl.git FUSE

WORKDIR /root/.julia/dev/FUSE
RUN make develop

RUN rm /root/.ssh/id_rsa