FROM --platform=linux/_PLATFORM_ julia:latest
RUN apt-get -y update
RUN apt-get -y install --no-install-recommends git make python3 pip net-tools

RUN pip3 install zmq tornado
RUN apt-get autoclean

WORKDIR /root/.julia/dev
COPY ./Broker Broker/
COPY ./CHEASE CHEASE/
COPY ./CoordinateConventions CoordinateConventions/
COPY ./EFIT EFIT/
COPY ./EPEDNN EPEDNN/
COPY ./Equilibrium Equilibrium/
COPY ./FiniteElementHermite FiniteElementHermite/
COPY ./Fortran90Namelists Fortran90Namelists/
COPY ./FUSE FUSE/
COPY ./FusionMaterials FusionMaterials/
COPY ./IMAS IMAS/
COPY ./IMASDD IMASDD/
COPY ./MillerExtendedHarmonic MillerExtendedHarmonic/
COPY ./NNeutronics NNeutronics/
COPY ./QED QED/
COPY ./TAUENN TAUENN/
COPY ./TGLFNN TGLFNN/
COPY ./VacuumFields VacuumFields/
COPY ./ZMQ ZMQ/

WORKDIR /root/.julia/dev/FUSE
RUN make rm_manifests
RUN make install_no_registry
RUN make precompile
WORKDIR /root/.julia/dev

# ports
EXPOSE 9999
EXPOSE 8888
EXPOSE 7777
EXPOSE 6666
