FROM --platform=linux/_PLATFORM_ julia_fuse__PLATFORM_:latest

WORKDIR /root/.julia/dev
COPY ./CHEASE CHEASE/
COPY ./CoordinateConventions CoordinateConventions/
COPY ./EFIT EFIT/
COPY ./EPEDNN EPEDNN/
COPY ./Equilibrium Equilibrium/
COPY ./FiniteElementHermite FiniteElementHermite/
COPY ./Fortran90Namelists Fortran90Namelists/
COPY ./FUSE FUSE/
COPY ./FusionMaterials FusionMaterials/
COPY ./IMAS IMAS/
COPY ./IMASDD IMASDD/
COPY ./MillerExtendedHarmonic MillerExtendedHarmonic/
COPY ./NNeutronics NNeutronics/
COPY ./QED QED/
COPY ./SimulationParameters SimulationParameters/
COPY ./TAUENN TAUENN/
COPY ./TGLFNN TGLFNN/
COPY ./VacuumFields VacuumFields/

WORKDIR /root/.julia/dev/FUSE
RUN make rm_manifests
RUN make precompile
WORKDIR /root/.julia/dev

