name: daily_manifest

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

env:
  PTP_READ_TOKEN: ${{ secrets.PTP_READ_TOKEN }}



concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.x"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      #============
      - name: Check if fuse bot commit
        run: |
          author=$(git log -1 --pretty=format:'%an')
          if [ "$author" = "fuse bot" ]; then
            echo "Skipping action due to commit made by 'fuse bot'."
            exit 78
          fi
      #============
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          show-versioninfo: true
      - uses: julia-actions/cache@v1
      - run: make install_ci
      - uses: julia-actions/julia-buildpkg@v1
      #============
      - uses: julia-actions/julia-runtest@v1
      - run: make manifest_ci_commit
      #============
      - name: Debug with tmate if failure + manual triggrer + debug mode
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
