name: interactive

on:
  workflow_dispatch:

env:
  PTP_READ_TOKEN: ${{ secrets.PTP_READ_TOKEN }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.x"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Set JULIA_NUM_THREADS=${{ steps.cpu-cores.outputs.count }}
        run: echo "JULIA_NUM_THREADS=${{ steps.cpu-cores.outputs.count }}" >> $GITHUB_ENV
      #============
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: pip install nbconvert
      #============
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          show-versioninfo: true
      - run: make install_ci
      - uses: julia-actions/julia-buildpkg@v1
      #============
      - name: Interactive with tmate
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
